group: travis_latest
language: python
python:
  - 2.7
  - 3.6
matrix:
  allow_failures:
    - python: 3.6
install:
  - pip install flake8 pytest psycopg2
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database infobase_test;' -U postgres
  #- psql -c 'create database infogami_test;' -U postgres # required for tests/test_infogami
  # stop the build if there are Python syntax errors
  - flake8 . --count --select=E9,F63,F7 --show-source --statistics
  # exit-zero if there are Python undefined names
  - flake8 . --count --exit-zero --select=F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - pytest infogami test tests
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
